apiVersion: v1
kind: Service
metadata:
  name: votingappresult-service
  labels:
    name: votingappresult-service
    type: frontend
spec:
  type: LoadBalancer
  selector:
    name: votingappresult-pod
    type: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008